web:
  restart: always
  build: ./
  expose:
    - "8000"
  #volumes:
   # - /usr/src/app
   # - /usr/src/app/static
  #env_file: .env
  environment:
    DEBUG: 'true'
  #command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000 

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/chaolife/static
  volumes_from:
    - web
  links:
    - web:web

